### ISSUE TITLE
Container upgrade Trusty to a later LTS {Xenial, Bionic}

### ISSUE THREAD

**Issue by TimJSwan89** [runtimeverification/rv-match_testing#10]
Two of {`dpkg`,`mawk`,`php-src`}, I'm almost certain it was {`dpkg`,`mawk`}, depended on linux being upgraded from `Trusty` to `Xenial`, but to ensure things are working and done cleanly, we may need a new source ubuntu container to copy from on the jenkins machine.

This issue expected to be closed when the upgrade proves to be successful, meaning, multiple projects are building with `kcc` properly and there are no major dependency issues, like apt not working, to effect a majority of the projects.

**Comment by TimJSwan89** [comment]
@shd101wyy showed me how he was using `lxc-create` on the `jenkins` project `rv-predict-lxc`.
The top level configure script right now is:
```
## configure lxc container
# mkdir -p ~/.config/lxc
# echo "lxc.id_map = u 0 1214112 65536" > ~/.config/lxc/default.conf
# echo "lxc.id_map = g 0 1214112 65536" >> ~/.config/lxc/default.conf
# echo "lxc.network.type = veth" >> ~/.config/lxc/default.conf
# echo "lxc.network.link = lxcbr0" >> ~/.config/lxc/default.conf

## create lxc container
# lxc-create -t download -n rvpredict-ubuntu-base -- -d ubuntu -r xenial -a amd64
# lxc-create -t download -n rvpredict-ubuntu-17-base -- -d ubuntu -r zesty -a amd64

## install packages
# lxc-start -n rvpredict-ubuntu-base
# lxc-attach -n rvpredict-ubuntu-base -- apt-get install -y openjdk-8-jdk-headless
# lxc-stop -n rvpredict-ubuntu-base

## list containers
# lxc-ls --fancy
```

It looks like I can even use `zesty` instead of just `xenial`, so the upgrade from `trusty` is +3 instead of +2 iterations.

**Comment by TimJSwan89** [comment]
@dwightguth recommended we use a `Long Term Support` version of Linux, which I understand applies to `bionic` and not `zesty`. Also, `bionic` is newer.

**Comment by shd101wyy** [comment]
I dont recommend you to use `bionic`. Because `18.04 LTS` is not even released yet..

`trusty` and `xenial` are good enough.

**Comment by TimJSwan89** [comment]
@shd101wyy Did you read the initial post? It says that 2 projects which do not build with `trusty` do build with `xenial`. So I need to figure out how to upgrade it and get the networking working.

**Comment by darko-marinov** [comment]
Can we ignore those two projects for now and get everything else working with one (older, stable) version before worrying about the latest version?

**Comment by TimJSwan89** [comment]
Our current status has been upgraded from `trusty` to `xenial` with the new LXD setup. This was introduced on the development branch which is now merged into master.
