### ISSUE TITLE
Installer for obtaining {kcc, k-bin-to-text}

### ISSUE THREAD

**Issue by TimJSwan89** [runtimeverification/rv-match_testing#30]
@shd101wyy @chathhorn and I discussed and based on both how long it takes the regression tests to run and just having a simpler project to deal with in general, I will no longer copy dependencies for {`kcc`,`k-bin-to-text`} directly from the `rv-match-master` jenkins project but rather be using the installer with the `- console` option from within the container.
https://github.com/runtimeverification/rv-match/blob/master/installer-linux/scripts/install-in-container
This is a tracker until that functionality is finally updated to the master branch.

**Comment by shd101wyy** [comment]
Only [line 5](https://github.com/runtimeverification/rv-match/blob/master/installer-linux/scripts/install-in-container#L5) is useful for you.

**Comment by TimJSwan89** [comment]
Completion threshold met with minimal success results. The tracking issue is no longer necessary.
