### ISSUE TITLE
is this a performance problem?

### ISSUE THREAD

**Issue by darko-marinov** [runtimeverification/rv-match_testing#53]
Does recompiling these support files with `kcc` take a lot of time (especially when thread may not be needed but only io.c): https://github.com/runtimeverification/rv-match_testing/blob/a7496e6e2af596327b0719aa634821e3d7b7bdbf/tests/JulietTestSuite-alt/match.sh#L304

**Comment by TimJSwan89** [comment]
Yes. They weren't compiled for each tests in the original perl scripts. I also modified the new scripts so that they also only compile them once at the beginning. Otherwise it is indeed inefficient.
